# k8s/pvcs.yaml
#
# Persistent Volume Claims for data storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: churn-prediction
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: churn-prediction
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs  # For shared uploads across pods

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: churn-prediction
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs